name: techtainable
favicon: null
layout_spectrum: 0.8726148253772408
typography_spectrum: 0.24657102301716805
title: 'Ramblings on Technology, Sustainability, and Life'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8389837003778666
  lightness: 0.769036901416257
  saturation: 0.8004214495886117
  rhythmicContrast: 0.6947290790267289
purpose: []
